const List<String> cities = [
  'Hanoi',
  'London',
  'New York',
  'Tokyo',
  'Paris',
  'Berlin',
  'Rio de Janeiro',
  'Istanbul',
  'Seoul',
  'Los Angeles',
];

// Bản đồ mô tả âm nhạc dựa trên điều kiện thời tiết
const Map<String, Map<String, dynamic>> weatherDescriptions = {
  'clear sky': {
    'description': '🎶 Vui tươi, năng lượng cao, dễ nhảy múa.',
    'min_energy': 0.7,
    'max_energy': 1.0,
    'target_energy': 0.9,
    'min_valence': 0.7,
    'target_valence': 0.9,
    'genres': ['pop', 'dance', 'electronic'],
  },
  'few clouds': {
    'description': '🎶 Vui vẻ, nhưng có chút nhẹ nhàng.',
    'min_energy': 0.5,
    'max_energy': 0.8,
    'target_energy': 0.65,
    'min_valence': 0.6,
    'target_valence': 0.75,
    'genres': ['indie', 'acoustic'],
  },
  'scattered clouds': {
    'description': '🎶 Bình yên, thư giãn, đôi khi mang hơi hướng tươi sáng.',
    'min_energy': 0.4,
    'max_energy': 0.7,
    'target_energy': 0.55,
    'min_valence': 0.5,
    'target_valence': 0.7,
    'genres': ['chill', 'lo-fi'],
  },
  'broken clouds': {
    'description': '🎶 Trầm lắng hơn, mang tính suy tư.',
    'min_energy': 0.3,
    'max_energy': 0.6,
    'target_energy': 0.45,
    'min_valence': 0.4,
    'target_valence': 0.5,
    'genres': ['jazz', 'blues'],
  },
  'overcast clouds': {
    'description': '🎶 Ẩm ướt, trầm lắng, đôi khi buồn bã.',
    'min_energy': 0.2,
    'max_energy': 0.5,
    'target_energy': 0.35,
    'min_valence': 0.2,
    'target_valence': 0.4,
    'genres': ['classical', 'ambient'],
  },
  'light intensity drizzle': {
    'description': '🎶 Nhẹ nhàng, dễ chịu, pha chút buồn.',
    'min_energy': 0.4,
    'max_energy': 0.6,
    'target_energy': 0.5,
    'min_valence': 0.5,
    'target_valence': 0.6,
    'genres': ['soft rock', 'chill'],
  },
  'drizzle': {
    'description': '🎶 Dịu dàng, thoải mái, nhưng có cảm giác lười biếng.',
    'min_energy': 0.3,
    'max_energy': 0.5,
    'target_energy': 0.4,
    'min_valence': 0.4,
    'target_valence': 0.5,
    'genres': ['indie pop', 'folk'],
  },
  'heavy intensity drizzle': {
    'description': '🎶 Đậm đà, mang tính cảm xúc mạnh.',
    'min_energy': 0.5,
    'max_energy': 0.7,
    'target_energy': 0.6,
    'min_valence': 0.3,
    'target_valence': 0.5,
    'genres': ['alternative', 'rock'],
  },
  'light rain': {
    'description': '🎶 Nhẹ nhàng, dễ chịu, pha chút buồn.',
    'min_energy': 0.4,
    'max_energy': 0.6,
    'target_energy': 0.5,
    'min_valence': 0.4,
    'target_valence': 0.5,
    'genres': ['acoustic', 'singer-songwriter'],
  },
  'moderate rain': {
    'description': '🎶 Chậm, u buồn, trầm mặc.',
    'min_energy': 0.3,
    'max_energy': 0.5,
    'target_energy': 0.4,
    'min_valence': 0.2,
    'target_valence': 0.4,
    'genres': ['indie rock', 'piano'],
  },
  'heavy intensity rain': {
    'description': '🎶 Mạnh mẽ, cảm xúc mãnh liệt, đôi khi sầu bi.',
    'min_energy': 0.5,
    'max_energy': 0.8,
    'target_energy': 0.65,
    'min_valence': 0.2,
    'target_valence': 0.4,
    'genres': ['post-rock', 'emo'],
  },
  'shower rain': {
    'description': '🎶 Cảm xúc, đôi chút sôi động nhưng ẩn chứa sự buồn bã.',
    'min_energy': 0.5,
    'max_energy': 0.7,
    'target_energy': 0.6,
    'min_valence': 0.3,
    'target_valence': 0.5,
    'genres': ['folk rock', 'soul'],
  },
  'thunderstorm': {
    'description': '🎶 Mạnh mẽ, kịch tính, năng lượng cao.',
    'min_energy': 0.7,
    'max_energy': 1.0,
    'target_energy': 0.85,
    'min_valence': 0.5,
    'target_valence': 0.7,
    'genres': ['hard rock', 'metal'],
  },
  'heavy thunderstorm': {
    'description': '🎶 Nhiệt huyết, căng thẳng, đầy cảm xúc.',
    'min_energy': 0.8,
    'max_energy': 1.0,
    'target_energy': 0.9,
    'min_valence': 0.4,
    'target_valence': 0.6,
    'genres': ['heavy metal', 'punk'],
  },
  'ragged thunderstorm': {
    'description': '🎶 Kịch tính, đầy sức mạnh và cảm xúc mãnh liệt.',
    'min_energy': 0.7,
    'max_energy': 0.9,
    'target_energy': 0.8,
    'min_valence': 0.3,
    'target_valence': 0.5,
    'genres': ['electronic', 'dubstep'],
  },
  'light snow': {
    'description': '🎶 Lãng mạn, nhẹ nhàng, cảm giác dịu dàng.',
    'min_energy': 0.3,
    'max_energy': 0.5,
    'target_energy': 0.4,
    'min_valence': 0.6,
    'target_valence': 0.8,
    'genres': ['chill', 'soft pop'],
  },
  'snow': {
    'description': '🎶 Lãng mạn, ấm áp, nhẹ nhàng.',
    'min_energy': 0.4,
    'max_energy': 0.6,
    'target_energy': 0.5,
    'min_valence': 0.5,
    'target_valence': 0.7,
    'genres': ['folk', 'classical'],
  },
  'heavy snow': {
    'description': '🎶 Mềm mại, thơ mộng, nhưng có cảm giác lạnh lẽo.',
    'min_energy': 0.2,
    'max_energy': 0.4,
    'target_energy': 0.3,
    'min_valence': 0.5,
    'target_valence': 0.6,
    'genres': ['ambient', 'new age'],
  },
  'mist': {
    'description': '🎶 Bí ẩn, trầm lắng, dễ gây suy tư.',
    'min_energy': 0.3,
    'max_energy': 0.5,
    'target_energy': 0.4,
    'min_valence': 0.4,
    'target_valence': 0.5,
    'genres': ['post-rock', 'instrumental'],
  },
  'smoke': {
    'description': '🎶 Đen tối, ma mị, u ám.',
    'min_energy': 0.2,
    'max_energy': 0.4,
    'target_energy': 0.3,
    'min_valence': 0.2,
    'target_valence': 0.4,
    'genres': ['gothic', 'dark ambient'],
  },
  'haze': {
    'description': '🎶 Dịu dàng, ấm áp, dễ chịu.',
    'min_energy': 0.4,
    'max_energy': 0.6,
    'target_energy': 0.5,
    'min_valence': 0.4,
    'target_valence': 0.6,
    'genres': ['chillout', 'jazz'],
  },
  'dust': {
    'description': '🎶 Độc đáo, lạ thường, có chút hoài cổ.',
    'min_energy': 0.4,
    'max_energy': 0.6,
    'target_energy': 0.5,
    'min_valence': 0.4,
    'target_valence': 0.5,
    'genres': ['retro', 'world music'],
  },
  'sand': {
    'description': '🎶 Năng động, mạnh mẽ, pha chút nhiệt đới.',
    'min_energy': 0.5,
    'max_energy': 0.7,
    'target_energy': 0.6,
    'min_valence': 0.5,
    'target_valence': 0.7,
    'genres': ['reggae', 'tropical'],
  },
  'ash': {
    'description': '🎶 U ám, lặng lẽ, có chút lôi cuốn.',
    'min_energy': 0.3,
    'max_energy': 0.5,
    'target_energy': 0.4,
    'min_valence': 0.2,
    'target_valence': 0.4,
    'genres': ['experimental', 'fusion'],
  },
  'squall': {
    'description': '🎶 Kịch tính, mạnh mẽ, đầy năng lượng.',
    'min_energy': 0.7,
    'max_energy': 1.0,
    'target_energy': 0.85,
    'min_valence': 0.4,
    'target_valence': 0.6,
    'genres': ['rock', 'metal'],
  },
  'tornado': {
    'description': '🎶 Bão tố, mãnh liệt, đầy sức mạnh.',
    'min_energy': 0.9,
    'max_energy': 1.0,
    'target_energy': 0.95,
    'min_valence': 0.3,
    'target_valence': 0.5,
    'genres': ['heavy metal', 'punk'],
  },
  'windy': {
    'description': '🎶 Thoải mái, thư giãn, nhẹ nhàng.',
    'min_energy': 0.4,
    'max_energy': 0.6,
    'target_energy': 0.5,
    'min_valence': 0.5,
    'target_valence': 0.7,
    'genres': ['folk', 'acoustic'],
  },
  'hurricane': {
    'description': '🎶 Mãnh liệt, mạnh mẽ, căng thẳng.',
    'min_energy': 0.8,
    'max_energy': 1.0,
    'target_energy': 0.9,
    'min_valence': 0.2,
    'target_valence': 0.4,
    'genres': ['metal', 'hardcore'],
  },
};
