const List<String> cities = [
  'Hanoi',
  'London',
  'New York',
  'Tokyo',
  'Paris',
  'Berlin',
  'Rio de Janeiro',
  'Istanbul',
  'Seoul',
  'Los Angeles',
];

// Bản đồ mô tả âm nhạc dựa trên điều kiện thời tiết
const Map<String, Map<String, dynamic>> weatherDescriptions = {
  'clear sky': {
    'description': '🎶 Vui tươi, năng lượng cao, dễ nhảy múa.',
    'min_energy': 0.7,
    'max_energy': 1.0,
    'target_energy': 0.9,
    'min_valence': 0.7,
    'target_valence': 0.9,
  },
  'few clouds': {
    'description': '🎶 Vui vẻ, nhưng có chút nhẹ nhàng.',
    'min_energy': 0.5,
    'max_energy': 0.8,
    'target_energy': 0.65,
    'min_valence': 0.6,
    'target_valence': 0.75,
  },
  'scattered clouds': {
    'description': '🎶 Bình yên, thư giãn, đôi khi mang hơi hướng tươi sáng.',
    'min_energy': 0.4,
    'max_energy': 0.7,
    'target_energy': 0.55,
    'min_valence': 0.5,
    'target_valence': 0.7,
  },
  'broken clouds': {
    'description': '🎶 Trầm lắng hơn, mang tính suy tư.',
    'min_energy': 0.3,
    'max_energy': 0.6,
    'target_energy': 0.45,
    'min_valence': 0.4,
    'target_valence': 0.5,
  },
  'overcast clouds': {
    'description': '🎶 Ẩm ướt, trầm lắng, đôi khi buồn bã.',
    'min_energy': 0.2,
    'max_energy': 0.5,
    'target_energy': 0.35,
    'min_valence': 0.2,
    'target_valence': 0.4,
  },
  'light intensity drizzle': {
    'description': '🎶 Nhẹ nhàng, dễ chịu, pha chút buồn.',
    'min_energy': 0.4,
    'max_energy': 0.6,
    'target_energy': 0.5,
    'min_valence': 0.5,
    'target_valence': 0.6,
  },
  'drizzle': {
    'description': '🎶 Dịu dàng, thoải mái, nhưng có cảm giác lười biếng.',
    'min_energy': 0.3,
    'max_energy': 0.5,
    'target_energy': 0.4,
    'min_valence': 0.4,
    'target_valence': 0.5,
  },
  'heavy intensity drizzle': {
    'description': '🎶 Đậm đà, mang tính cảm xúc mạnh.',
    'min_energy': 0.5,
    'max_energy': 0.7,
    'target_energy': 0.6,
    'min_valence': 0.3,
    'target_valence': 0.5,
  },
  'light rain': {
    'description': '🎶 Nhẹ nhàng, dễ chịu, pha chút buồn.',
    'min_energy': 0.4,
    'max_energy': 0.6,
    'target_energy': 0.5,
    'min_valence': 0.4,
    'target_valence': 0.5,
  },
  'moderate rain': {
    'description': '🎶 Chậm, u buồn, trầm mặc.',
    'min_energy': 0.3,
    'max_energy': 0.5,
    'target_energy': 0.4,
    'min_valence': 0.2,
    'target_valence': 0.4,
  },
  'heavy intensity rain': {
    'description': '🎶 Mạnh mẽ, cảm xúc mãnh liệt, đôi khi sầu bi.',
    'min_energy': 0.5,
    'max_energy': 0.8,
    'target_energy': 0.65,
    'min_valence': 0.2,
    'target_valence': 0.4,
  },
  'shower rain': {
    'description': '🎶 Cảm xúc, đôi chút sôi động nhưng ẩn chứa sự buồn bã.',
    'min_energy': 0.5,
    'max_energy': 0.7,
    'target_energy': 0.6,
    'min_valence': 0.3,
    'target_valence': 0.5,
  },
  'thunderstorm': {
    'description': '🎶 Mạnh mẽ, kịch tính, năng lượng cao.',
    'min_energy': 0.7,
    'max_energy': 1.0,
    'target_energy': 0.85,
    'min_valence': 0.5,
    'target_valence': 0.7,
  },
  'heavy thunderstorm': {
    'description': '🎶 Nhiệt huyết, căng thẳng, đầy cảm xúc.',
    'min_energy': 0.8,
    'max_energy': 1.0,
    'target_energy': 0.9,
    'min_valence': 0.4,
    'target_valence': 0.6,
  },
  'ragged thunderstorm': {
    'description': '🎶 Kịch tính, đầy sức mạnh và cảm xúc mãnh liệt.',
    'min_energy': 0.7,
    'max_energy': 0.9,
    'target_energy': 0.8,
    'min_valence': 0.3,
    'target_valence': 0.5,
  },
  'light snow': {
    'description': '🎶 Lãng mạn, nhẹ nhàng, cảm giác dịu dàng.',
    'min_energy': 0.3,
    'max_energy': 0.5,
    'target_energy': 0.4,
    'min_valence': 0.6,
    'target_valence': 0.8,
  },
  'snow': {
    'description': '🎶 Lãng mạn, ấm áp, nhẹ nhàng.',
    'min_energy': 0.4,
    'max_energy': 0.6,
    'target_energy': 0.5,
    'min_valence': 0.5,
    'target_valence': 0.7,
  },
  'heavy snow': {
    'description': '🎶 Mềm mại, thơ mộng, nhưng có cảm giác lạnh lẽo.',
    'min_energy': 0.2,
    'max_energy': 0.4,
    'target_energy': 0.3,
    'min_valence': 0.5,
    'target_valence': 0.6,
  },
  'mist': {
    'description': '🎶 Bí ẩn, trầm lắng, dễ gây suy tư.',
    'min_energy': 0.3,
    'max_energy': 0.5,
    'target_energy': 0.4,
    'min_valence': 0.4,
    'target_valence': 0.5,
  },
  'smoke': {
    'description': '🎶 Đen tối, ma mị, u ám.',
    'min_energy': 0.2,
    'max_energy': 0.4,
    'target_energy': 0.3,
    'min_valence': 0.2,
    'target_valence': 0.4,
  },
  'haze': {
    'description': '🎶 Nhẹ nhàng, thoải mái, không quá căng thẳng.',
    'min_energy': 0.4,
    'max_energy': 0.6,
    'target_energy': 0.5,
    'min_valence': 0.5,
    'target_valence': 0.7,
  },
  'dust': {
    'description': '🎶 Lạnh lùng, mạnh mẽ, đôi khi bí ẩn.',
    'min_energy': 0.3,
    'max_energy': 0.5,
    'target_energy': 0.4,
    'min_valence': 0.3,
    'target_valence': 0.5,
  },
  'sand': {
    'description': '🎶 Sức mạnh, đầy năng lượng nhưng cũng mang chút bí ẩn.',
    'min_energy': 0.5,
    'max_energy': 0.7,
    'target_energy': 0.6,
    'min_valence': 0.5,
    'target_valence': 0.7,
  },
  'fog': {
    'description': '🎶 Dịu dàng, nhẹ nhàng, nhưng có cảm giác mơ hồ.',
    'min_energy': 0.3,
    'max_energy': 0.5,
    'target_energy': 0.4,
    'min_valence': 0.4,
    'target_valence': 0.6,
  },
  'volcanic ash': {
    'description': '🎶 U tối, cảm xúc mạnh, đôi khi gợi cảm giác thất vọng.',
    'min_energy': 0.2,
    'max_energy': 0.4,
    'target_energy': 0.3,
    'min_valence': 0.2,
    'target_valence': 0.4,
  },
  'squall': {
    'description': '🎶 Năng lượng mạnh, kích thích cảm xúc mãnh liệt.',
    'min_energy': 0.6,
    'max_energy': 0.8,
    'target_energy': 0.7,
    'min_valence': 0.5,
    'target_valence': 0.7,
  },
  'tornado': {
    'description': '🎶 Cường độ cao, nhịp điệu nhanh, cảm xúc mãnh liệt.',
    'min_energy': 0.8,
    'max_energy': 1.0,
    'target_energy': 0.9,
    'min_valence': 0.3,
    'target_valence': 0.5,
  },
  'duststorm': {
    'description': '🎶 Mạnh mẽ, hỗn loạn, đầy cảm xúc.',
    'min_energy': 0.5,
    'max_energy': 0.7,
    'target_energy': 0.6,
    'min_valence': 0.4,
    'target_valence': 0.6,
  },
};
